### ISSUE TITLE
mix gleam.test warning about dependencies

### ISSUE THREAD

**Issue by georgesboris** [gleam-lang/mix_gleam#41] opened 2024-04-19 09:29 UTC
Currently, with a minimal project using the exact same setup as the example in this repo, I get the following warning when running `mix gleam.test`  

> The module `gleeunit` is being imported, but `gleeunit`, the package it
> belongs to, is not a direct dependency of your package.
> In a future version of Gleam this may become a compile error.
>
> Run this command to add it to your dependencies:
>
>    gleam add gleeunit

The tests run normally since `gleeunit`  is present on my mix dependencies.
Is this to be ignored for now? Or am I missing any setup step?

**Comment by lpil** [comment] 2024-04-19 11:30
Hello! Duplicate of https://github.com/gleam-lang/mix_gleam/issues/38

**Closed as not planned by lpil** 2024-04-19 11:30 UTC
